
package Sistema;

/**
 *
 * @author alexhp
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame2
     */
    
    public MainFrame() {
        initComponents();
        
        PanelVentas.setVisible(false);
        PanelAdmin.setVisible(false);
        PanelUserInfo.setVisible(false);
    }
    
    boolean estadoLogin = false;
    private int nivelUsuario;
    
    
    // metodo para Actualizar la informacion del usuario que inicio secion
    public void actualizarLabelsUsuario(String nombreUsuario, String apellidoUsuario, String userNivel) {
        lblUsername.setText("Usuario: " + nombreUsuario + " " + apellidoUsuario);
        lblNivel.setText(userNivel);
    }
    
    //Metodo para actualizar el estado del programa segun el usuario
    public void ActualizarEstadoLogin(boolean estado, int nivelUsuario) {
        // Activar o desactivar los paneles generales
        PanelVentas.setVisible(estado);
        PanelUserInfo.setVisible(estado);

        if (nivelUsuario == 3) { 
            PanelAdmin.setVisible(estado);
        } else {
            PanelAdmin.setVisible(false);
        }
    }
    
    public void setNivelUsuario(int nivelUsuario) {
        this.nivelUsuario = nivelUsuario;
    }
    
    // Metodos para activar o desactivar botone desde las ventasnas internas de ijframe
    public void activarBotonCerrarSesision(){
        btnLogOff.setEnabled(true);
    }
    
    public void desacativarLogInBoton(){
        btnEntrar.setEnabled(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDesktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_imgLogo = new javax.swing.JLabel();
        PanelUserInfo = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        PanelVentas = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lblAdminInventario = new javax.swing.JLabel();
        lblAdminVentas = new javax.swing.JLabel();
        lblAdminClientes = new javax.swing.JLabel();
        btnInventario = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        PanelAdmin = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        lblAdminUsuarios = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        btnLogOff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainDesktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainDesktopPane.setPreferredSize(new java.awt.Dimension(1200, 800));

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1262, Short.MAX_VALUE)
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbl_imgLogo.setIcon(new javax.swing.ImageIcon("/Users/alexhp/Downloads/logo(1).png")); // NOI18N

        PanelUserInfo.setEnabled(false);

        lblBienvenido.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBienvenido.setText("Bienvenido");

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblUsername.setText("username");
        lblUsername.setFocusTraversalKeysEnabled(false);
        lblUsername.setFocusable(false);

        lblNivel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblNivel.setText("UsernameNivel");
        lblNivel.setFocusable(false);

        javax.swing.GroupLayout PanelUserInfoLayout = new javax.swing.GroupLayout(PanelUserInfo);
        PanelUserInfo.setLayout(PanelUserInfoLayout);
        PanelUserInfoLayout.setHorizontalGroup(
            PanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserInfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNivel)
                    .addComponent(lblUsername))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBienvenido)
                .addGap(67, 67, 67))
        );
        PanelUserInfoLayout.setVerticalGroup(
            PanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNivel)
                .addContainerGap())
        );

        PanelVentas.setEnabled(false);

        lblAdminInventario.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAdminInventario.setText("Administrador de Inventario");

        lblAdminVentas.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAdminVentas.setText("Administrador de Ventas");

        lblAdminClientes.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAdminClientes.setText("Administrador de Clientes");

        btnInventario.setText("Inventario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVentasLayout = new javax.swing.GroupLayout(PanelVentas);
        PanelVentas.setLayout(PanelVentasLayout);
        PanelVentasLayout.setHorizontalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentasLayout.createSequentialGroup()
                .addGroup(PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVentasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdminClientes)
                            .addGroup(PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAdminInventario, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAdminVentas)
                                .addGroup(PanelVentasLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnVentas)))
                            .addGroup(PanelVentasLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInventario)
                                    .addComponent(btnClientes))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        PanelVentasLayout.setVerticalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentasLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdminInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventario)
                .addGap(31, 31, 31)
                .addComponent(lblAdminVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVentas)
                .addGap(28, 28, 28)
                .addComponent(lblAdminClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelAdmin.setEnabled(false);

        lblAdminUsuarios.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAdminUsuarios.setText("Administrador de usuarios");

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminLayout = new javax.swing.GroupLayout(PanelAdmin);
        PanelAdmin.setLayout(PanelAdminLayout);
        PanelAdminLayout.setHorizontalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnUsuarios)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelAdminLayout.createSequentialGroup()
                        .addComponent(lblAdminUsuarios)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelAdminLayout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addGap(26, 26, 26))))
        );
        PanelAdminLayout.setVerticalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdminUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnEntrar.setText("Iniciar Sesion");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnLogOff.setText("Cerrar Sesion");
        btnLogOff.setEnabled(false);
        btnLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEntrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogOff)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_imgLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_imgLogo)
                .addGap(18, 18, 18)
                .addComponent(PanelUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(btnLogOff))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOffActionPerformed
        // TODO add your handling code here:
        //Cierrar las IJframes abiertos
        mainDesktopPane.removeAll();
        mainDesktopPane.repaint();

        //Cambiamos el estado login del sistema
        ActualizarEstadoLogin(false, 0);

        // Regresamos los campos a predeterminados
        lblUsername.setText("");
        lblNivel.setText("");
        btnEntrar.setEnabled(true);
        btnLogOff.setEnabled(false);
    }//GEN-LAST:event_btnLogOffActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        mainDesktopPane.removeAll();
        JIFrame_LogIn JIFlogin = new JIFrame_LogIn(mainDesktopPane, this);
        mainDesktopPane.add(JIFlogin);
        JIFlogin.setVisible(true);
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        // Abrir FrmUsuarios
        JIFrame_Usuarios JIFusuarios = new JIFrame_Usuarios(mainDesktopPane, this);
        mainDesktopPane.add(JIFusuarios);
        JIFusuarios.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        JIFrame_Clientes JIFclientes = new JIFrame_Clientes(mainDesktopPane, this.nivelUsuario);
        mainDesktopPane.add(JIFclientes);
        JIFclientes.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        JIFrame_Ventas JIFventas = new JIFrame_Ventas(mainDesktopPane, this.nivelUsuario);
        mainDesktopPane.add(JIFventas);
        JIFventas.setVisible(true);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        JIFrame_Inventario JIFinventario = new JIFrame_Inventario(mainDesktopPane, this.nivelUsuario);
        mainDesktopPane.add(JIFinventario);
        JIFinventario.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdmin;
    private javax.swing.JPanel PanelUserInfo;
    private javax.swing.JPanel PanelVentas;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnLogOff;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAdminClientes;
    private javax.swing.JLabel lblAdminInventario;
    private javax.swing.JLabel lblAdminUsuarios;
    private javax.swing.JLabel lblAdminVentas;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbl_imgLogo;
    private javax.swing.JDesktopPane mainDesktopPane;
    // End of variables declaration//GEN-END:variables
}
